spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: 12345

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: true